version: "3"
services:
  app:
    build: ./app
    ports:
      - "8080:8080"

  integration:
    build: ./app
    environment: 
     - INTEGRATION_BASE_URL=http://app:8080
    working_dir: /lbcfb/src/api
    command: go test
    depends_on:
     - app
      
      
